### ISSUE TITLE
Launch Screen tab bar doesn't extend to bottom of screen

### ISSUE THREAD

**Issue by aaronbrethorst** [OneBusAway/OBAKit#368] opened 2021-05-14 02:35 UTC
See screenshot. The tab bar is only about 44pt tall and there's a white gap underneath it. The tab bar should be anchored to the screen bottom, not the safe area.

![image](https://user-images.githubusercontent.com/2254/118213193-4f76b700-b422-11eb-9ed5-a3cd1a24ae51.png)

**Comment by ualch9** [comment] 2021-05-14 02:42
dupe of #346

**Closed** 2021-05-14 02:42 UTC
Labels: Fit & Finish
